name: "build and publish web-client docker image"

on: 
    push: 
        branches: ['main']
        paths: 
            'services/web-client'

jobs: 
    build-and-publish: 
        runs-on: 'ubuntu-latest'
        steps: 
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up QEMU for multi-platform support
              uses: docker/setup-qemu-action@v1
      
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./services/web-client/Dockerfile
                push: true
                tags: ghcr.io/mykalmachon/shlink-web-client-railway:${{ github.sha }}, ghcr.io/mykalmachon/shlink-web-client-railway:latest
                cache-from: type=gha
                cache-to: type=gha,mode=max